=== hk-lrzy/HWind/target/classes/hwind.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:beans="http://www.springframework.org/schema/beans">

    <xsd:import namespace="http://www.springframework.org/schema/beans"/>
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>
    <!--拦截器部分定义-->
    <xsd:element name="interceptor-def">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="class" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="interceptor-ref">
        <xsd:complexType>
            <xsd:attribute name="ref" type="xsd:attribute" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="interceptor-stack">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="interceptor" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="mapping" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:attribute name="path" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="exclude-mapping" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:attribute name="path" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:choice maxOccurs="unbounded">
                                <xsd:element ref="interceptor-def"/>
                                <xsd:element ref="interceptor-ref"/>
                            </xsd:choice>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!--拦截器结束-->

    <!--pack开始-->
    <xsd:element name="pack">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="channel" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="param" form="unqualified" maxOccurs="unbounded" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:attribute name="name" use="required" type="xsd:string"/>
                                    <xsd:attribute name="type" use="required" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="namespace" type="xsd:string" use="required"/>
                        <xsd:attribute name="name" type="xsd:string"/>
                        <xsd:attribute name="class" type="xsd:string" use="required"/>
                        <xsd:attribute name="method" type="xsd:string" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="namespace" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <!--pack结束-->

    <!--config定义-->
    <xsd:element name="hwinds">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="interceptor-def" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="interceptor-stack" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="pack" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== hk-lrzy/HWind/src/main/resources/hwind.xml
<?xml version="1.0" encoding="UTF-8"?>
<hwinds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="hwind.xsd">

    <interceptor-def name="haoke" class="org.hklrzy.hwind.interceptor.HWindInterceptorChain"/>

    <interceptor-stack>
        <interceptor>
            <mapping path="/**"/>
            <exclude-mapping path="/api"/>
            <interceptor-ref ref="haoke"/>
        </interceptor>
    </interceptor-stack>

    <pack namespace="/">
        <channel namespace="/api" class="com" method="index">
            <param name="haoke" type="me"/>
        </channel>
    </pack>
</hwinds>
